### ISSUE TITLE
Error de tipeo en la práctica 2

### ISSUE THREAD

**Issue by joaquinmuzzi** [santiagotrini/ejercicios-algo#1]
En la consigna declara la función g y la llama con f, eso debería dar error pero no existe como respuesta al ejercicio

![image](https://github.com/santiagotrini/ejercicios-algo/assets/155847816/fbf8984e-2f92-4853-8fb2-ba77d213947d)

**Comment by santiagotrini** [comment]
Ahí lo arreglé, gracias! :+1:
